export const CREATE_JOURNAL_ENTRY = 'journal/CREATE_JOURNAL_ENTRY';
export const CREATE_JOURNAL_ENTRY_SUCCESS = 'journal/CREATE_JOURNAL_ENTRY_SUCCESS';
export const CREATE_JOURNAL_ENTRY_FAILED = 'journal/CREATE_JOURNAL_ENTRY_FAILED';

export const UPDATE_JOURNAL_ENTRY = 'journal/UPDATE_JOURNAL_ENTRY';
export const UPDATE_JOURNAL_ENTRY_SUCCESS = 'journal/UPDATE_JOURNAL_ENTRY_SUCCESS';
export const UPDATE_JOURNAL_ENTRY_FAILED = 'journal/UPDATE_JOURNAL_ENTRY_FAILED';

export const DELETE_JOURNAL_ENTRY = 'journal/DELETE_JOURNAL_ENTRY';
export const DELETE_JOURNAL_ENTRY_SUCCESS = 'journal/DELETE_JOURNAL_ENTRY_SUCCESS';
export const DELETE_JOURNAL_ENTRY_FAILED = 'journal/DELETE_JOURNAL_ENTRY_FAILED';

export const GET_JOURNAL = 'journal/GET_JOURNAL';
export const GET_JOURNAL_SUCCESS = 'journal/GET_JOURNAL_SUCCESS';
export const GET_JOURNAL_FAILED = 'journal/GET_JOURNAL_FAILED';
