export const CREATE_JOURNAL_ENTRY = 'quests/CREATE_JOURNAL_ENTRY';
export const CREATE_JOURNAL_ENTRY_SUCCESS = 'quests/CREATE_JOURNAL_ENTRY_SUCCESS';
export const CREATE_JOURNAL_ENTRY_FAILED = 'quests/CREATE_JOURNAL_ENTRY_FAILED';

export const UPDATE_JOURNAL_ENTRY = 'quests/UPDATE_JOURNAL_ENTRY';
export const UPDATE_JOURNAL_ENTRY_SUCCESS = 'quests/UPDATE_JOURNAL_ENTRY_SUCCESS';
export const UPDATE_JOURNAL_ENTRY_FAILED = 'quests/UPDATE_JOURNAL_ENTRY_FAILED';

export const DELETE_JOURNAL_ENTRY = 'quests/DELETE_JOURNAL_ENTRY';
export const DELETE_JOURNAL_ENTRY_SUCCESS = 'quests/DELETE_JOURNAL_ENTRY_SUCCESS';
export const DELETE_JOURNAL_ENTRY_FAILED = 'quests/DELETE_JOURNAL_ENTRY_FAILED';

export const GET_JOURNAL = 'quests/GET_JOURNAL';
export const GET_JOURNAL_SUCCESS = 'quests/GET_JOURNAL_SUCCESS';
export const GET_JOURNAL_FAILED = 'quests/GET_JOURNAL_FAILED';
